apps/reimburse/urls.py
from django.urls import path
from .views import ReimburseCreateView, ReimburseDeleteView, ReimburseDetailView, ReimburseUpdateView, ReimburseListView

app_name = 'reimburse'

urlpatterns = [
    path('', ReimburseListView.as_view(), name='reimburse'),
    path('reimburse-create/', ReimburseCreateView.as_view(), name='reimburse-create'),
    path('reimburse-detail/<uuid:uuid>', ReimburseDetailView.as_view(), name='reimburse-detail'),
    path('reimburse-update/<uuid:uuid>', ReimburseUpdateView.as_view(), name='reimburse-update'),
    path('reimburse-delete/<uuid:uuid>', ReimburseDeleteView.as_view(), name= 'reimburse-delete' ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import handler404
from .views import error400, error403, error404, error500

handler400 = error400
handler403 = error403
handler404 = error404
handler500 = error500

urlpatterns = [
    path('', include('apps.account.urls')),
    path('admin/', admin.site.urls),
    path('advance/', include('apps.advance.urls')),
    path('client/', include('apps.client.urls')),
    path('company/', include('apps.company.urls')),
    path('project/', include('apps.project.urls')),
    path('reimburse/', include('apps.reimburse.urls')),
    path('timesheet/', include('apps.timesheet.urls')),
]

apps/reimburse/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model
from apps.project.models import Project
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class ReimburseChoices(models.TextChoices):
    transport   = 'transport',_('Transport')
    hotel       = 'hotel',_('Hotel')
    meal        = 'meal',_('Meal')
    other       = 'other',_('Other')

class StatusChoices(models.TextChoices):
    open    = 'open',_('Open')
    approve = 'approve',_('Approve')
    close   = 'close',_("Close")

class Reimburse(models.Model):    
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Projects')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Users")
    name = models.CharField(max_length=50, verbose_name='Name')
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code')
    category = models.CharField(max_length=30, choices=ReimburseChoices.choices, default=ReimburseChoices.transport, verbose_name='Category')
    description = models.TextField(verbose_name='Description')
    date = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Date')
    ammount = models.CharField(max_length=9, verbose_name='Ammount')
    status = models.CharField(max_length=15, choices=StatusChoices.choices, default=StatusChoices.open, verbose_name='Status')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Created Date')
    approve_date = models.DateTimeField(blank=True, null=True, auto_now=False, auto_now_add=False, verbose_name='Approve Date')
    approve_by = models.CharField(blank=True, max_length=50, verbose_name='Approve By')
    approve_note = models.TextField(blank=True, verbose_name='Approve Note')
    close_date = models.DateTimeField(blank=True, null=True, auto_now=False, auto_now_add=False, verbose_name='Close Date')
    close_by = models.CharField(blank=True, max_length=50, verbose_name='Close By')
    close_note = models.TextField(blank=True, verbose_name='Close Note')

    class Meta:
        verbose_name = 'reimburse'
        verbose_name_plural = 'reimburses'
        db_table = 'reimburse'
        ordering = ['project', 'user', 'name', 'category', 'status', 'date']
        permissions = [('approve_reimburse', 'Can approve reimburse'), ('close_reimburse', 'Can close reimburse'), ]
        indexes = [
            models.Index(fields=['project', 'user', 'name', 'uuid',  'category', 'status', 'date',]),
        ]
        default_related_name = 'Reimburses'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.status == 'approve' and not self.approve_date:
            self.approve_date = timezone.now()
        elif self.status == 'close' and not self.close_date:
            if not self.approve_date:
                self.approve_date = timezone.now()
            self.close_date = timezone.now()
        super().save(*args, **kwargs)

apps/reimburse/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    Field,
    Submit,
)
from .models import Reimburse

class ReimburseForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.label_class = 'form-label mt-3'
        self.helper.layout = Layout(
            Field('project', css_class='form-select'),
            Field('name', placeholder='Name'),
            Field('category', css_class='form-select'),
            Field('description', placeholder='Contact'),
            Field('date'),
            Field('ammount', placeholder='Ammount'),
            Field('status', css_class='form-select'),
    )
        
    class Meta:
        model = Reimburse
        exclude = ['user','uuid']
        widgets = {
            'date' : forms.TextInput(attrs={'type': 'date', 'min':'2018-01-01', 'max':'2030-12-31'}),
        }

apps/reimburse/views.py
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import Reimburse
from .forms import ReimburseForm
from copy import copy

class ReimburseMixin(LoginRequiredMixin, SuccessMessageMixin, object):
    model = Reimburse
    template_name = "reimburse/reimburse_form.html"
    form_class = ReimburseForm
    success_url = reverse_lazy('reimburse:reimburse')
    success_message = None
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    extra_context = {
        'site_title'    : 'epci | reimburse',
        'page_title'    : 'reimburse list',
    }
    
    def get_queryset(self):
        queryset = Reimburse.objects.filter(user=self.request.user)
        return queryset
    
class ReimburseListView(ReimburseMixin, ListView):
    template_name = "reimburse/reimburse.html"
    context_object_name = 'reimburses'
    paginate_by = 10
class ReimburseCreateView(ReimburseMixin, CreateView):
    success_message = "%(name)s was created successfully"
    extra_context = copy(ReimburseMixin.extra_context)
    extra_context['form_name'] = 'form create reimburse'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ReimburseDetailView(ReimburseMixin, DetailView):
    template_name = 'reimburse/reimburse_detail.html'

class ReimburseUpdateView(ReimburseMixin, UpdateView):
    success_message = "%(name)s was updated successfully"
    extra_context = copy(ReimburseMixin.extra_context)
    extra_context['form_name'] = 'form update reimburse'
    
class ReimburseDeleteView(ReimburseMixin, DeleteView):
    template_name = 'reimburse/reimburse_delete.html'
    success_message = "%(name)s was deleted successfully"
    
    def delete(self, request, *args, **kwargs):
        from django.contrib import messages
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super().delete(request, *args, **kwargs)

apps/reimburse/templates/reimburse/reimburse.html
{% extends 'frontend/base.html' %}
{% load i18n static %}

{% block page_title_option %}
<div class="text-muted mt-1">{{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }}
    reimburse</div>{% endblock page_title_option %}
{% block page_title_action %}
<div class="col-auto ms-auto d-print-none">
    <div class="d-flex">
        <input type="search" class="form-control d-inline-block w-9 me-3" placeholder="Search…" />
        <a href="{% url 'reimburse:reimburse-create' %}" class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <line x1="12" y1="5" x2="12" y2="19" />
                <line x1="5" y1="12" x2="19" y2="12" /></svg>
            New reimburse
        </a>
    </div>
</div>
{% endblock page_title_action %}
{% block content %}
{% if messages %}
{% for message in messages  %}
<div class="alert alert-important alert-{{ message.tags }} alert-dismissible" role="alert">
    <div class="d-flex">
        <div>
            <!-- SVG icon code with class="alert-icon" -->
        </div>
        <div>
            {{ message }}
        </div>
    </div>
    <a class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="close"></a>
</div>
{% endfor %}
{% endif %}
<div class="row row-cards"> 
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Reimburse</h3>
            </div>
            <div class="table-responsive">
                <table class="table card-table table-vcenter">
                    <thead>
                        <td>Status</td>
                        <td>Description</td>
                        <td>Category</td>
                        <td>Project</td>
                        <td>Date</td>
                        <td colspan="2" class="text-center"></td>
                    </thead>
                    <tbody>
                        {% for reimburse in reimburses %} 
                        <tr>
                            <td>
                                <span class="avatar avatar-sm">{{ reimburse.status|make_list|first|title }}</span>
                            </td>
                            <td>
                                {{ reimburse.name }}
                            </td>
                            <td class="text-nowrap text-muted">
                                {{ reimburse.category }}
                            </td>
                            <td class="text-nowrap text-muted">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3" />
                                    <line x1="12" y1="12" x2="20" y2="7.5" /><line x1="12" y1="12" x2="12" y2="21" />
                                    <line x1="12" y1="12" x2="4" y2="7.5" /><line x1="16" y1="5.25" x2="8" y2="9.75" />
                                </svg>
                                {{ reimburse.project }}
                            </td>
                            <td class="text-nowrap text-muted">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <rect x="4" y="5" width="16" height="16" rx="2"></rect>
                                    <line x1="16" y1="3" x2="16" y2="7"></line>
                                    <line x1="8" y1="3" x2="8" y2="7"></line>
                                    <line x1="4" y1="11" x2="20" y2="11"></line>
                                    <line x1="11" y1="15" x2="12" y2="15"></line>
                                    <line x1="12" y1="15" x2="12" y2="18"></line>
                                </svg>
                                {{ reimburse.date|date:'d F Y' }}
                            </td>
                            <td>
                                <a href="{% url 'reimburse:reimburse-update' uuid=reimburse.uuid %}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4" /><line x1="13.5" y1="6.5" x2="17.5" y2="10.5" /></svg>
                                Edit</a>
                            </td>
                            <td>
                                <a href="{% url 'reimburse:reimburse-delete' uuid=reimburse.uuid %}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="4" y1="7" x2="20" y2="7" /><line x1="10" y1="11" x2="10" y2="17" /><line x1="14" y1="11" x2="14" y2="17" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
                                Delete
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr><td colspan=7><p class="text-center">No data found</p></td></tr>
                        {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% if page_obj.number %}
<div class="d-flex fixed-bottom mb-5">
    <ul class="pagination ms-auto">
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
            <a class="page-link"
                href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                    stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <polyline points="15 6 9 12 15 18" /></svg>
                prev
            </a>
        </li>
        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
            <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">
                next <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                    stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <polyline points="9 6 15 12 9 18" /></svg>
            </a>
        </li>
    </ul>
</div>
{% endif %}
{% block delete %}{% endblock delete %}
{% endblock content %}

apps/reimburse/templates/reimburse/reimburse_delete.html
{% extends 'reimburse/reimburse.html' %}
{% block delete %}    
<div class="modal modal-blur fade show" id="modal-danger" tabindex="-1" style="padding-right: 16px; display: block;" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
      <div class="modal-content">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="modal-status bg-danger"></div>
        <div class="modal-body text-center py-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon mb-2 text-danger icon-lg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 9v2m0 4v.01"></path><path d="M5 19h14a2 2 0 0 0 1.84 -2.75l-7.1 -12.25a2 2 0 0 0 -3.5 0l-7.1 12.25a2 2 0 0 0 1.75 2.75"></path></svg>
          <h3>Are you sure?</h3>
          <div class="text-muted">Do you really want to remove? What you've done cannot be undone.</div>
        </div>
        <form method="POST">{% csrf_token %}
        <div class="modal-footer">
          <div class="w-100">
            <div class="row">
              <div class="col"><a href="{% url 'reimburse:reimburse' %}" class="btn btn-white w-100" data-bs-dismiss="modal">
                  Cancel
                </a></div>
              <div class="col">
                  <button type="submit" class="btn btn-danger w-100" data-bs-dismiss="modal">
                  Delete
                </button>
            </div>
            </div>
          </div>
        </div>
        </form>
      </div>
    </div>
</div>
{% endblock delete %}

apps/reimburse/templates/reimburse/reimburse_form.html
{% extends 'frontend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}   
<div class="row row-cards">
    <div class="col-12">
        <form class="form-horizontal" method="post">
        <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ form_name|default:'Form'|title}}</h4>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
        <div class="card-footer text-end">
            <div class="d-flex">
                <a href="{% url 'reimburse:reimburse' %}" class="btn btn-link">Cancel</a>
                <button type="submit" class="btn btn-primary ms-auto">Submit</button>
            </div>
        </div>
        </form>
    </div>
</div>
{% endblock content %}