apps/client/urls.py
from django.urls import path
from .views import ClientCreateView, ClientDeleteView, ClientDetailView, ClientUpdateView, ClientListView

app_name = 'client'

urlpatterns = [
    path('', ClientListView.as_view(), name='client'),
    path('client-create/', ClientCreateView.as_view(), name='client-create'),
    path('client-detail/<uuid:uuid>', ClientDetailView.as_view(), name='client-detail'),
    path('client-update/<uuid:uuid>', ClientUpdateView.as_view(), name='client-update'),
    path('client-delete/<uuid:uuid>', ClientDeleteView.as_view(), name= 'client-delete' ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import handler404
from .views import error400, error403, error404, error500

handler400 = error400
handler403 = error403
handler404 = error404
handler500 = error500

urlpatterns = [
    path('', include('apps.account.urls')),
    path('admin/', admin.site.urls),
    path('advance/', include('apps.advance.urls')),
    path('client/', include('apps.client.urls')),
    path('company/', include('apps.company.urls')),
    path('project/', include('apps.project.urls')),
    path('reimburse/', include('apps.reimburse.urls')),
    path('timesheet/', include('apps.timesheet.urls')),
]

apps/client/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.company.models import Company
from .validators import validate_contact

class DepartmentChoices(models.TextChoices):
    project = 'project', _('Project')
    engineering = 'engineering', _('Engineering')
    purchasing = 'puchasing', _('Puchasing')
    accounting = 'accounting', _('Accounting')
    other = 'other', _('Other')

class Client(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    department = models.CharField(max_length=20, choices=DepartmentChoices.choices,  default=DepartmentChoices.project, verbose_name="Department")
    name = models.CharField(max_length=30, verbose_name="Username")
    contact = models.CharField(validators = [validate_contact], max_length=12, blank=True, verbose_name="Contact")
    email = models.EmailField(max_length=30,blank=True, verbose_name="Email")
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')
    publish = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients'
        db_table = 'client'
        ordering = ['name', 'uuid']
        unique_together = [['name', 'uuid']]
        permissions = [('publish_client', 'Can publish client')]
        indexes = [
            models.Index(fields=['name', 'uuid','department','company']),
        ]
        default_related_name = 'Clients'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('client-detail', kwargs={'uuid': self.uuid})
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
    
    # def __get_initial_name(self):
    #     return self.name[:1]
    
    # iname = property(__get_initial_name)

apps/client/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    Field,
    Submit,
)
from .models import Client

class ClientForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        #self.helper.form_class = 'form-horizontal'
        self.helper.form_tag = False
        self.helper.label_class = 'form-label mt-3'
        self.helper.layout = Layout(
            Field('department', css_class='form-select'),
            Field('name', placeholder='Username'),
            Field('contact', placeholder='Contact'),
            Field('email', placeholder='Email'),
            Field('company', css_class='form-select'),
            #Submit('submit', 'Submit', css_class='float-right')  # define your signup button here
    )
        
    class Meta:
        model = Client
        exclude = ['uuid']

apps/client/views.py
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, ListView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import Client
from .forms import ClientForm
from copy import copy

class ClientMixin(LoginRequiredMixin, SuccessMessageMixin, object):
    model = Client
    template_name = "client/client_form.html"
    form_class = ClientForm
    success_url = reverse_lazy('client:client')
    success_message = None
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    extra_context = {
        'site_title'    : 'epci | customer users',
        'page_title'    : 'client list',
    }
    
class ClientListView(ClientMixin, ListView):
    template_name = "client/client.html"
    context_object_name = 'clients'
    paginate_by = 10

class ClientCreateView(ClientMixin, CreateView):
    success_message = "%(name)s was created successfully"
    extra_context = copy(ClientMixin.extra_context)
    extra_context['form_name'] = 'form create client'

class ClientDetailView(ClientMixin, DetailView):
    template_name = 'client/client_detail.html'

class ClientUpdateView(ClientMixin, UpdateView):
    success_message = "%(name)s was updated successfully"
    extra_context = copy(ClientMixin.extra_context)
    extra_context['form_name'] = 'form update client'
    
class ClientDeleteView(ClientMixin, DeleteView):
    template_name = 'client/client_delete.html'
    success_message = "%(name)s was deleted successfully"
    
    def delete(self, request, *args, **kwargs):
        from django.contrib import messages
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super().delete(request, *args, **kwargs)

apps/client/templates/client/client.html
{% extends 'frontend/base.html' %}
{% load i18n static %}

{% block page_title_option %}
<div class="text-muted mt-1">{{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }} clients</div>{% endblock page_title_option %}
{% block page_title_action %}
<div class="col-auto ms-auto d-print-none">
    <div class="d-flex">
      <input type="search" class="form-control d-inline-block w-9 me-3" placeholder="Search…"/>
      <a href="{% url 'client:client-create' %}" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
        New client
      </a>
    </div>
</div>
{% endblock page_title_action %}  
{% block content %}
{% if messages %}
{% for message in messages  %}  
<div class="alert alert-important alert-{{ message.tags }} alert-dismissible" role="alert">
  <div class="d-flex">
    <div>
      <!-- SVG icon code with class="alert-icon" -->
    </div>
    <div>
      {{ message }}
    </div>
  </div>
  <a class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="close"></a>
</div>
{% endfor %}
{% endif %}
<div class="row row-cards">
  {% for value in clients %}
  <div class="col-md-6 col-lg-3">
    <div class="card">
      <div class="card-body p-4 text-center">
        <span class="avatar avatar-xl mb-3 avatar-rounded">{{ value.name|make_list|first|title }}
          {% comment %}{{ value.|make_list|slice:'1:'|join:''|title }}{% endcomment %}</span>
        <h3 class="m-0 mb-1"><a href="{% url 'client:client-detail' uuid=value.uuid %}">{{ value.name|title }}</a></h3>
        <div class="text-muted">{{ value.department|default:'None'|title }}</div>
        <div class="mt-3">
          <span class="badge bg-purple-lt">{{ value.company.name|title }}</span>
        </div>
      </div>
      <div class="d-flex">
        <a href="#" class="card-btn"><svg xmlns="http://www.w3.org/2000/svg" class="icon me-2 text-muted" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><rect x="3" y="5" width="18" height="14" rx="2" /><polyline points="3 7 12 13 21 7" /></svg>
          Email</a>
        <a href="#" class="card-btn"><svg xmlns="http://www.w3.org/2000/svg" class="icon me-2 text-muted" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5 4h4l2 5l-2.5 1.5a11 11 0 0 0 5 5l1.5 -2.5l5 2v4a2 2 0 0 1 -2 2a16 16 0 0 1 -15 -15a2 2 0 0 1 2 -2" /></svg>
          Call</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% if page_obj.number %}    
<div class="d-flex fixed-bottom mb-5">
    <ul class="pagination ms-auto">
      <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
        <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="15 6 9 12 15 18" /></svg>
          prev
        </a>
      </li>
      {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">
          next <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="9 6 15 12 9 18" /></svg>
        </a>
      </li>
    </ul>
</div>
{% endif %}
{% endblock content %}

apps/client/templates/client/client_delete.html
{% extends 'client/client_detail.html' %}
{% block delete %}    
<div class="modal modal-blur fade show" id="modal-danger" tabindex="-1" style="padding-right: 16px; display: block;" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
      <div class="modal-content">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="modal-status bg-danger"></div>
        <div class="modal-body text-center py-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon mb-2 text-danger icon-lg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 9v2m0 4v.01"></path><path d="M5 19h14a2 2 0 0 0 1.84 -2.75l-7.1 -12.25a2 2 0 0 0 -3.5 0l-7.1 12.25a2 2 0 0 0 1.75 2.75"></path></svg>
          <h3>Are you sure?</h3>
          <div class="text-muted">Do you really want to remove? What you've done cannot be undone.</div>
        </div>
        <form method="POST">{% csrf_token %}
        <div class="modal-footer">
          <div class="w-100">
            <div class="row">
              <div class="col"><a href="{% url 'client:client' %}" class="btn btn-white w-100" data-bs-dismiss="modal">
                  Cancel
                </a></div>
              <div class="col">
                  <button type="submit" class="btn btn-danger w-100" data-bs-dismiss="modal">
                  Delete
                </button>
            </div>
            </div>
          </div>
        </div>
        </form>
      </div>
    </div>
</div>
{% endblock delete %}

apps/client/templates/client/client_detail.html
{% extends 'frontend/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4">
      <div class="card">
        <div class="card-status-top bg-info"></div>
        <div class="card-body p-4 text-center mt-4">
            <div class="d-flex flex-column align-items-center text-center">
                <span class="avatar avatar-xl mb-2 avatar-rounded" style="height:150px!important;width:150px!important">{{ client.name|make_list|first|title }}</span>
                <div class="text-center">
                    <h1 class="mb-1">{{ client.name|title }}</h1>
                    <p class="text-muted mb-1">{{ client.department|title }}</p>
                    <p class="badge bg-green-lt">{{ client.company|title }}</p>
                </div>
                <div class="mt-1">
                    <a href="{% url 'client:client-update' uuid=client.uuid%}" type="button" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4" /><line x1="13.5" y1="6.5" x2="17.5" y2="10.5" /></svg>
                        Edit</a>
                        <a href="{% url 'client:client-delete' uuid=client.uuid%}" type="button" class="btn btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="4" y1="7" x2="20" y2="7" /><line x1="10" y1="11" x2="10" y2="17" /><line x1="14" y1="11" x2="14" y2="17" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
                        Delete</a>
                </div>
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="card mb-3">
        <div class="card-status-top bg-info"></div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-3">
                    <h4 class="text-capitalize mb-0">Name</h4>
                </div>
                <div class="col-sm-9 text-muted">
                    {{ client.name|title}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h4 class="text-capitalize mb-0">Company</h4>
                </div>
                <div class="col-sm-9 text-muted">
                  {{ client.company.name|title }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                    <h4 class="text-capitalize mb-0">Department</h4>
                </div>
                <div class="col-sm-9 text-muted">
                {{ client.department|title}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h4 class="text-capitalize mb-0">Email</h4>
                </div>
                <div class="col-sm-9 text-muted">
                {{ client.email|default:'--Empty--'}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h4 class="text-capitalize mb-0">Contact</h4>
                </div>
                <div class="col-sm-9 text-muted">
                    {{ client.contact|default:'--Empty--'}}
                </div>
            </div>
        </div>
      </div>
    </div>
</div>
{% block delete %}{% endblock delete %}
{% endblock content %}

apps/client/templates/client/client_form.html
{% extends 'frontend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}   
<div class="row row-cards">
    <div class="col-12">
        <form class="form-horizontal" method="post">
        <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ form_name|default:'Form'|title}}</h4>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
        <div class="card-footer text-end">
            <div class="d-flex">
                <a href="{% url 'client:client' %}" class="btn btn-link">Cancel</a>
                <button type="submit" class="btn btn-primary ms-auto">Submit</button>
            </div>
        </div>
        </form>
    </div>
</div>
{% endblock content %}