apps/project/urls.py
from django.urls import path
from .views import ProjectCreateView, ProjectDeleteView, ProjectDetailView, ProjectUpdateView, ProjectListView

app_name = 'project'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project'),
    path('project-create/', ProjectCreateView.as_view(), name='project-create'),
    path('project-detail/<uuid:uuid>', ProjectDetailView.as_view(), name='project-detail'),
    path('project-update/<uuid:uuid>', ProjectUpdateView.as_view(), name='project-update'),
    path('project-delete/<uuid:uuid>', ProjectDeleteView.as_view(), name= 'project-delete' ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import handler404
from .views import error400, error403, error404, error500

handler400 = error400
handler403 = error403
handler404 = error404
handler500 = error500

urlpatterns = [
    path('', include('apps.account.urls')),
    path('admin/', admin.site.urls),
    path('advance/', include('apps.advance.urls')),
    path('client/', include('apps.client.urls')),
    path('company/', include('apps.company.urls')),
    path('project/', include('apps.project.urls')),
    path('reimburse/', include('apps.reimburse.urls')),
    path('timesheet/', include('apps.timesheet.urls')),
]

apps/project/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from apps.client.models import Client
from django.core.exceptions import ValidationError

class ProjectChoices(models.TextChoices):
    open = 'open', _('Open')
    close = 'close', _('Close')

class Project(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Client")
    name = models.CharField(max_length=50, unique=True, verbose_name="Name")
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, verbose_name="Code")
    start_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name="Start Date")
    end_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name="End Date")
    description = models.TextField(blank=True, verbose_name="Description")
    worker = models.ManyToManyField(get_user_model(), verbose_name="Workers")
    status = models.CharField(max_length=15, choices=ProjectChoices.choices, default=ProjectChoices.open, verbose_name="Status")
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = 'project'
        verbose_name_plural = 'projects'
        db_table = 'project'
        ordering = ['client', 'name',  'uuid']
        unique_together = [['name', 'uuid']]
        permissions = [('close_poject', 'Can close project')]
        indexes = [
            models.Index(fields=['client', 'name', 'uuid']),
        ]
        default_related_name = 'Projects'

    def __str__(self):
        return self.name
    
    # def clean(self):
    #     if self.start_date < self.end_date:
    #         raise ValidationError({
    #                 'start_date': ValidationError(_('Please correct date input.'), code='invalid'),
    #                 'end_date': ValidationError(_('Please correct date input'), code='invalid'),
    #         })
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
    def __get_worker(self):
        return ",".join([str(p) for p in self.worker.all()])
    
    workers = property(__get_worker)

apps/project/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    Field,
    Submit,
)
from .models import Project

class ProjectForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.label_class = 'form-label mt-3'
        self.helper.layout = Layout(
            Field('client', css_class='form-select'),
            Field('name', placeholder='Username'),
            Field('description', placeholder='Contact'),
            Field('start_date'),
            Field('end_date'),
            Field('worker', css_class='form-select'),
            Field('status', css_class='form-select'),
    )
        
    class Meta:
        model = Project
        exclude = ['created_at', 'uuid']
        # widgets = {
        #     'start_date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select start date', 'type':'date', 'min':'2018-01-01', 'max':'2030-12-31'}),
        #     'end_date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select end date', 'type':'date', 'min':'2018-01-01', 'max':'2030-12-31'}),
        # }
        widgets = {
            'start_date' : forms.TextInput(attrs={'type': 'date', 'min':'2018-01-01', 'max':'2030-12-31'}),
            'end_date' : forms.TextInput(attrs={'type': 'date', 'min':'2018-01-01', 'max':'2030-12-31'}),
        }

apps/project/views.py
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, PermissionDenied
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import Project
from .forms import ProjectForm
from copy import copy

class ProjectMixin(LoginRequiredMixin, PermissionRequiredMixin, PermissionDenied, SuccessMessageMixin, object):
    model = Project
    template_name = "project/project_form.html"
    form_class = ProjectForm
    success_url = reverse_lazy('project:project')
    success_message = None
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    extra_context = {
        'site_title'    : 'epci | project',
        'page_title'    : 'project list',
    }
    
    def get_queryset(self):
        queryset = Project.objects.filter(worker=self.request.user)
        return queryset
    
class ProjectListView(ProjectMixin, ListView):
    permission_required  = 'project.view_project'
    template_name = "project/project.html"
    context_object_name = 'projects'
    paginate_by = 10

class ProjectCreateView(ProjectMixin, CreateView):
    permission_required  = 'project.add_project'
    permission_denied_message = 'no have access for this action'
    success_message = "%(name)s was created successfully"
    extra_context = copy(ProjectMixin.extra_context)
    extra_context['form_name'] = 'form create project'

class ProjectDetailView(ProjectMixin, DetailView):
    template_name = 'project/project_detail.html'

class ProjectUpdateView(ProjectMixin, UpdateView):
    success_message = "%(name)s was updated successfully"
    extra_context = copy(ProjectMixin.extra_context)
    extra_context['form_name'] = 'form update project'
    
class ProjectDeleteView(ProjectMixin, DeleteView):
    template_name = 'project/project_delete.html'
    success_message = "%(name)s was deleted successfully"
    
    def delete(self, request, *args, **kwargs):
        from django.contrib import messages
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super().delete(request, *args, **kwargs)

apps/project/templates/project/project.html
{% extends 'frontend/base.html' %}
{% load i18n static %}

{% block page_title_option %}
<div class="text-muted mt-1">{{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }}
    project</div>{% endblock page_title_option %}
{% block page_title_action %}
<div class="col-auto ms-auto d-print-none">
    <div class="d-flex">
        <input type="search" class="form-control d-inline-block w-9 me-3" placeholder="Search…" />
        <a href="{% url 'project:project-create' %}" class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <line x1="12" y1="5" x2="12" y2="19" />
                <line x1="5" y1="12" x2="19" y2="12" /></svg>
            New project
        </a>
    </div>
</div>
{% endblock page_title_action %}
{% block content %}
{% if messages %}
{% for message in messages  %}
<div class="alert alert-important alert-{{ message.tags }} alert-dismissible" role="alert">
    <div class="d-flex">
        <div>
            <!-- SVG icon code with class="alert-icon" -->
        </div>
        <div>
            {{ message }}
        </div>
    </div>
    <a class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="close"></a>
</div>
{% endfor %}
{% endif %}
<div class="row row-cards"> 
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Project</h3>
            </div>
            <div class="table-responsive">
                <table class="table card-table table-vcenter">
                    <thead>
                        <td>Status</td>
                        <td>Description</td>
                        <td>Start Date</td>
                        <td>End Date</td>
                        <td>Client</td>
                        <td colspan="2" class="text-center"></td>
                    </thead>
                    <tbody>
                        {% for project in projects %} 
                        <tr>
                            <td>
                                <span class="avatar avatar-sm">{{ project.status|make_list|first|title }}</span>
                            </td>
                            <td class="w-90">
                                <a href="{% url 'project:project-detail' uuid=project.uuid %}" class="text-reset">{{ project.name }}: [{{ project.workers}}]</a>
                            </td>
                            <td class="text-nowrap text-muted">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><rect x="4" y="5" width="16" height="16" rx="2" /><line x1="16" y1="3" x2="16" y2="7" /><line x1="8" y1="3" x2="8" y2="7" /><line x1="4" y1="11" x2="20" y2="11" /><line x1="10" y1="16" x2="14" y2="16" /><line x1="12" y1="14" x2="12" y2="18" /></svg>
                                {{ project.start_date|date:'d F Y' }}
                            </td>
                            <td class="text-nowrap text-muted">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><rect x="4" y="5" width="16" height="16" rx="2" /><line x1="16" y1="3" x2="16" y2="7" /><line x1="8" y1="3" x2="8" y2="7" /><line x1="4" y1="11" x2="20" y2="11" /><line x1="10" y1="16" x2="14" y2="16" /></svg>
                                {{ project.end_date|date:'d F Y' }}
                            </td>
                            <td class="text-nowrap text-muted">
                                {{ project.client }}
                            </td>
                            <td>
                                <a href="{% url 'project:project-update' uuid=project.uuid %}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4" /><line x1="13.5" y1="6.5" x2="17.5" y2="10.5" /></svg>
                                Edit</a>
                            </td>
                            <td>
                                <a href="{% url 'project:project-delete' uuid=project.uuid %}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="4" y1="7" x2="20" y2="7" /><line x1="10" y1="11" x2="10" y2="17" /><line x1="14" y1="11" x2="14" y2="17" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
                                Delete
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr><td colspan=7><p class="text-center">No data found</p></td></tr>
                        {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% if page_obj.number %}
<div class="d-flex fixed-bottom mb-5">
    <ul class="pagination ms-auto">
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
            <a class="page-link"
                href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                    stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <polyline points="15 6 9 12 15 18" /></svg>
                prev
            </a>
        </li>
        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
            <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">
                next <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                    stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <polyline points="9 6 15 12 9 18" /></svg>
            </a>
        </li>
    </ul>
</div>
{% endif %}
{% block delete %}{% endblock delete %}
{% endblock content %}

apps/project/templates/project/project_delete.html
{% extends 'project/project.html' %}
{% block delete %}    
<div class="modal modal-blur fade show" id="modal-danger" tabindex="-1" style="padding-right: 16px; display: block;" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
      <div class="modal-content">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="modal-status bg-danger"></div>
        <div class="modal-body text-center py-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon mb-2 text-danger icon-lg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 9v2m0 4v.01"></path><path d="M5 19h14a2 2 0 0 0 1.84 -2.75l-7.1 -12.25a2 2 0 0 0 -3.5 0l-7.1 12.25a2 2 0 0 0 1.75 2.75"></path></svg>
          <h3>Are you sure?</h3>
          <div class="text-muted">Do you really want to remove? What you've done cannot be undone.</div>
        </div>
        <form method="POST">{% csrf_token %}
        <div class="modal-footer">
          <div class="w-100">
            <div class="row">
              <div class="col"><a href="{% url 'project:project' %}" class="btn btn-white w-100" data-bs-dismiss="modal">
                  Cancel
                </a></div>
              <div class="col">
                  <button type="submit" class="btn btn-danger w-100" data-bs-dismiss="modal">
                  Delete
                </button>
            </div>
            </div>
          </div>
        </div>
        </form>
      </div>
    </div>
</div>
{% endblock delete %}

apps/project/templates/project/project_detail.html
{% extends 'frontend/base.html' %}
{% load i18n static %}

{% block content %}
<div class="row row-cards">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Project Detail</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-auto">
                        <h3>Client : </h3>
                    </div>
                    <div class="col-auto">
                        <p class="text-left">{{ project.client|title }}</p>
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-auto">
                        <h3>Name : </h3>
                    </div>
                    <div class="col-auto">
                        <p class="text-left">{{ project.name|title }}</p>
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-auto">
                        <h3>Description : </h3>
                    </div>
                    <div class="col-auto">
                        <p class="text-justify">{{ project.description }}</p>
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-auto">
                        <h3>Start Date: </h3>
                    </div>
                    <div class="col-auto">
                        <p class="text-left">{{ project.start_date }}</p>
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-auto">
                        <h3>End Date: </h3>
                    </div>
                    <div class="col-auto">
                        <p class="text-left">{{ project.end_date }}</p>
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-auto">
                        <h3>Workers: </h3>
                    </div>
                    <div class="col-auto">
                        <p class="text-left">[{{ project.workers|title }}]</p>
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-auto">
                        <h3>Status : </h3>
                    </div>
                    <div class="col-auto">
                        <p class="text-left">{{ project.status|title }}</p>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/project/templates/project/project_form.html
{% extends 'frontend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}   
<div class="row row-cards">
    <div class="col-12">
        <form class="form-horizontal" method="post">
        <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ form_name|default:'Form'|title}}</h4>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
        <div class="card-footer text-end">
            <div class="d-flex">
                <a href="{% url 'project:project' %}" class="btn btn-link">Cancel</a>
                <button type="submit" class="btn btn-primary ms-auto">Submit</button>
            </div>
        </div>
        </form>
    </div>
</div>
{% endblock content %}